### ISSUE TITLE
NanoPI M4 max frequency restores back after changing

### ISSUE THREAD

**Issue by stakanich** [ayaromenok/MD#1]
Hi! I'm trying to increase a max_frequency of my NanoPi M4 GPU. 
I found your repository and changed "/sys/class/misc/mali0/device/devfreq/ff9a0000.gpu/max_freq" to 800000000 (it was 200000000) and added this row to "/etc/rc.local".
I'm using friendlyarm and "/sys/class/misc/mali0/device/devfreq/ff9a0000.gpu/governor" was in "performance" state already.
But when I try to read *...*/max_freq with cat, it is not stable. It changes from 800000000 to 200000000 and to 800000000 again.
Did you have such issues? If you had, how did you solve it? Thank you in advance.

**Comment by stakanich** [comment]
Found the problem. It was a temperature. When it was 70 and higher, max_freq decreased somehow and returned back when it fall. Sorry for bothering.

**Comment by ayaromenok** [comment]
Nice to know, that you find a solution. 

Please note that this board with a very hot chip at the bottom required very good cooling system. I use a huge heat sink from old AMD Athlon 64 Desktop CPU(something like 200 gram and with size slightly bigger than NanoPi itself) - and it's not always enough. Also a GPU - with only 4 execution units - looks like slightly overclocked from beginning.
